2023-01-17 03:10:02.417 GMT Thread[#1,main,5,main] Cleanup action starting
java.sql.SQLException: Failed to start database 'C:\Users\Rowine\MyDB', see the next exception for details.
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at com.jdbc.DCpET.main(DCpET.java:15)
Caused by: java.sql.SQLException: Failed to start database 'C:\Users\Rowine\MyDB', see the next exception for details.
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 13 more
Caused by: java.sql.SQLException: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	... 10 more
Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.privGetJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.getJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.RawStore.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.access.RAMAccessManager.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.bootStore(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startProviderService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Unknown Source)
	... 10 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at com.jdbc.DCpET.main(DCpET.java:15)
Caused by: java.sql.SQLException: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 12 more
Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.privGetJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.getJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.RawStore.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.access.RAMAccessManager.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.bootStore(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startProviderService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Unknown Source)
	... 10 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
java.sql.SQLException: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at com.jdbc.DCpET.main(DCpET.java:15)
Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.privGetJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.getJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.RawStore.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.access.RAMAccessManager.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.bootStore(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startProviderService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Unknown Source)
	... 10 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
ERROR XSDB6: Another instance of Derby may have already booted the database C:\Users\Rowine\MyDB.
	at derby@10.5.1000001/org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.privGetJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.getJBMSLockOnDB(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.data.BaseDataFileFactory.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.raw.RawStore.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.store.access.RAMAccessManager.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.bootStore(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startProviderService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at derby@10.5.1000001/org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at com.jdbc.DCpET.main(DCpET.java:15)
============= end nested exception, level (3) ===========
Cleanup action completed
